for(i = 999999999999999999999999999999999999999; i < 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999; i++) { 
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
}
for(i = 999999999999999999999999999999999999999; i < 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999; i++) { 
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
    console.log("yes")
    console.log("xd")
    console.log("nou")
    console.log("aww")
    console.log("Stress test ur cpu")
    console.log("sowwy")
    console.log("im bored")
    console.log("so")
    console.log("i made")
    console.log("this")
    console.log("beautiful")
    console.log("app")
}

// Some PCs can have bad times running this stress tool.